### ISSUE TITLE
Install fmt/* in include/libsemigroups/fmt/

### ISSUE THREAD

**Issue by isuruf** [libsemigroups/libsemigroups#145]
Currently they are installed in `include/fmt` which can conflict with other fmt installation.

Or maybe use an external one. Can fmt 6.1.2 be used with libsemigroups?

**Comment by james-d-mitchell** [comment]
Thanks for the report @isuruf , I'll try to fix this today too. 

About fmt-6.1.2 I'm not sure, I haven't tried, I'll do some experimenting and see what I can come up with.

**Comment by james-d-mitchell** [comment]
It seems that `libsemigroups` works just fine with fmt-6.1.2

**Comment by james-d-mitchell** [comment]
Resolved in v1.0.4
