### ISSUE TITLE
Wrong lib name in pc file

### ISSUE THREAD

**Issue by antonio-rojas** [libsemigroups/libsemigroups#151]
In 1.0.4 the compiled library is called libsemigroups-1.0.so, but the pc file has Libs: -lsemigroups

**Comment by james-d-mitchell** [comment]
Thanks for the report @antonio-rojas I didn’t think of that, I’ll fix it today!

**Comment by isuruf** [comment]
@james-d-mitchell, sorry I didn't respond sooner. In https://github.com/libsemigroups/libsemigroups/pull/148, did you meant to change the library name to `libsemigroups-1.0.so` or to something like `libsemigroups.so` which is a symlink to `libsemigroups.so.1`?

**Comment by james-d-mitchell** [comment]
No problems, thanks for all your help. I think I did mean to do that following some advice I read somewhere, is it preferable to rename it as `libsemigroups.so.1`? If so, how?

**Comment by isuruf** [comment]
See https://github.com/libsemigroups/libsemigroups/pull/152
That way, you can still do `-lsemigroups`, but the resulting executable or shared library will link to `libsemigroups.so.1` instead of `libsemigroups.so`

**Comment by james-d-mitchell** [comment]
Thanks @isuruf super helpful!

**Comment by james-d-mitchell** [comment]
Resolved in v1.0.5
