### ISSUE TITLE
Configurator should define HPCOMBI_ASSERT

### ISSUE THREAD

**Issue by hivert** [libsemigroups/libsemigroups#165]
I created a macro `HPCOMBI_ASSERT` which should be defined to `LIBSEMIGROUPS_ASSERT` when compiling with `HPCombi` and is left blank currently. If I understand correctly, a consequence is that with `libsemigroup_cppyy` the test
```
BooleanMat([[True], [False]])
```
doesn't raise any error where it should.

**Comment by james-d-mitchell** [comment]
I think we resolved this, no? @hivert
