### ISSUE TITLE
docs/docs directory in release tarballs

### ISSUE THREAD

**Issue by jamesjer** [libsemigroups/libsemigroups#173]
The release tarballs have a docs directory which contains a docs directory which contains the actual documentation.  The scripts in etc break when confronted with these nested docs directories.  There is no such nesting in the git repo, so whatever creates the release tarballs must be doing it.

**Comment by james-d-mitchell** [comment]
Thanks for the report @jamesjer! I'm not currently sure why/how this is happening, but I'll try to get it fixed asap.

**Comment by james-d-mitchell** [comment]
Ok so the culprit is the single character "/" after `docs` in line 156 of `Makefile.am`. Preparing PR now...

**Comment by james-d-mitchell** [comment]
Resolved in v1.0.6
