### ISSUE TITLE
GAP's Manual book "Changes" becomes CHANGES.md 

### ISSUE THREAD

**Issue by dimpase** [libsemigroups/libsemigroups#178]
https://github.com/gap-system/gap/pull/3886 removed GAP's Manual book "Changes" and converted it into Markdown file. 

In view of this, `docs/docs/make.bat` might have to be changed.

**Comment by dimpase** [comment]
it's probably OK, in fact, as I most probably mixed up libsemigroups' docs and GAP's docs here. Sorry for noise -althought a test would be good, just in case.

**Comment by james-d-mitchell** [comment]
Libsemigroups has no dependence on GAP, I’m not sure how the changes you’ve made could impact libsemigroups at all. Can you perhaps explain what you imagine the issue with this might be?

**Comment by dimpase** [comment]
some GAP packages merge their docs with the main GAP docs, and the PR in question affected at least one of them.  But, indeed, looks like libsemigroups is a false positive. Sorry for noise.
