### ISSUE TITLE
Documentation for `fmt` dependency outdated?

### ISSUE THREAD

**Issue by fingolfin** [libsemigroups/libsemigroups#226]
I tried to build the code in this repository, but this failed because apparently I am missing `fmt`. I am told:
> fmt is required, clone or download the repo from https://github.com/fmtlib/fmt into the libsemigroups/extern directory

But doing that didn't actually work, at least for me. Indeed, it seems to be looking for content in directory `extern/fmt-5.3.0` instead. I tried renaming the symlink, but still doesn't work -- apparently somewhere between fmt 5.3.0 and the current 7.0.3 there were breaking changes in the API?

Perhaps the configure message should instead direct the user to download `https://github.com/fmtlib/fmt/releases/download/5.3.0/fmt-5.3.0.zip` ? Or perhaps you could even do that for the user if the dir is missing (using a script like <https://github.com/gap-packages/NormalizInterface/blob/master/etc/download.sh>). Or simply include a copy of that code in this repository?

**Comment by james-d-mitchell** [comment]
Thanks @fingolfin, good point! I'll be happy to fix this in the next release, including a copy in the repo is probably the most straightforward thing to do.

**Comment by james-d-mitchell** [comment]
Resolved by PR #228.
