### ISSUE TITLE
extern/.EIGEN_VERSION is missing from the release tarball

### ISSUE THREAD

**Issue by antonio-rojas** [libsemigroups/libsemigroups#236]
The release tarball can't be compiled against a system eigen because the extern/.EIGEN_VERSION file is not present, so the configure check fails. The file is present in the github-generated tar.gz though.

**Comment by james-d-mitchell** [comment]
@antonio-rojas Thanks for the report! I noticed this too, will prepare another release to include the missing file shortly.

**Comment by james-d-mitchell** [comment]
Resolved in v1.3.1.
