### ISSUE TITLE
Migrate from Travis to Github Actions

### ISSUE THREAD

**Issue by flsmith** [libsemigroups/libsemigroups#254]
Because of the changes detailed [here](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing), Travis is probably unsuitable for use as our CI now. Max Horn suggested using Github actions (as can be seen in this [WIP PR](https://github.com/gap-system/gap/pull/4036)), and I think it's the right call. For public repositories, it doesn't have a usage cap, and it seems to have all the relevant features that Travis did.

**Comment by james-d-mitchell** [comment]
I think I've more or less resolved this in PR #255. The only outstanding thing that I couldn't get to work (after a little while of trying) was the GAP tests. It seems relatively easy to use docker containers with github actions, but something goes wrong with the permissions in the `actions/checkout@v2` step below.

~~~~
   gap:
      runs-on: ubuntu-latest
      container: 
         image: gapsystem/gap-docker
         options: --user gap 
      steps:
         - uses: actions/checkout@v2
         - name: "Install dependencies . . ."
           run: |
                sudo apt-get install --yes git libtool-bin
         - name: "Run GAP Semigroups package tests . . ."
           run: bash ci/docker-gap.sh
~~~~

The errors this generates can be seen at (for example):

https://github.com/libsemigroups/libsemigroups/runs/1359563179?check_suite_focus=true

I wonder if @alexkonovalov or @fingolfin have any ideas about how to resolve this? This isn't a `libsemigroups` question but rather a github actions or gap-docker question. One solution would be to just install GAP from scratch, but I'd rather get the docker container working if possible. 

If the GAP team wants to have its own action for packages (as @fingolfin mentioned in a recent email to the GAP forum), then this could be part of one route to that, so  might be of wider interest than just for `libsemigroups`.

**Comment by fingolfin** [comment]
Thanks, this is interesting. Unfortunately I cannot really help, as I am also not a docker nor GitHub actions expert (which is part of the reason why I am not taking care of it this time around: While I am in principle always happy to learn new things and do the deep dive, I simply have too many other things on my plate right now. Anyway, I hope you can figure it out.

**Comment by james-d-mitchell** [comment]
Thanks for the comments @fingolfin, I managed to set things up on azure pipelines. I think I'm going to close this issue now.

**Comment by fingolfin** [comment]
@james-d-mitchell you may still want to update the badge in your README.md
