### ISSUE TITLE
Some issues with `Konieczny::add_generators`

### ISSUE THREAD

**Issue by james-d-mitchell** [libsemigroups/libsemigroups#416]
Here are some issues that I've observed with `Konieczny` when adding bindings to `libsemigroups_pybind11`:

~~~
    using Transf = LeastTransf<16>;
    Konieczny<Transf> S({Transf({1, 0, 2, 3, 4})});
    S.add_generator(Transf({1, 2, 3, 4, 0}));
    S.add_generator(Transf({0, 0, 2, 3, 4}));

    REQUIRE(S.generator(0) == Transf({1, 0, 2, 3, 4}));
    REQUIRE(S.generator(1) == Transf({1, 2, 3, 4, 0}));  # fails with  { 0, 1, 2, 3, 4 } == { 1, 2, 3, 4, 0 }
    REQUIRE(S.generator(2) == Transf({0, 0, 2, 3, 4}));
~~~

A similar but different issue is:

~~~
    Konieczny<Transf> S;
    S.add_generator(Transf({1, 2, 3, 4, 0}));
    S.add_generator(Transf({0, 0, 2, 3, 4}));

    REQUIRE(S.degree() == UNDEFINED); # should be 5!
    REQUIRE(S.number_of_generators() == 1); # passes!
~~~

I'm not sure what's going on @flsmith, any comments welcome! I can work around these in `libsemigroups_pybind11` but thought I'd record these here!

**Comment by flsmith** [comment]
I'm not sure that 

`REQUIRE(S.degree() == 5)`

makes sense - the degree of `Transf` seems to be 16.

Thoughts @james-d-mitchell ?

**Comment by james-d-mitchell** [comment]
Depends on what type Transf is, but 16 is one ok answer!
