### ISSUE TITLE
Add  `presentation::add_commutes_rule`

### ISSUE THREAD

**Issue by james-d-mitchell** [libsemigroups/libsemigroups#470]
I.e.

~~~
presentation::add_commutes_rule(p, "ababbaba", "bbb") // adds ababbababbb = bbbababbaba
~~~

Possibly also `presentation::add_commutator_rule` but at the moment I'm struggling to figure out what the arguments to this would be since we don't track inverses.

**Comment by Joseph-Edwards** [comment]
This feature was seemingly added a while ago (see [here](https://github.com/libsemigroups/libsemigroups/blob/3e9ab19b4a81d82ee6a16ee3f87d4f00cb5c0893/include/libsemigroups/presentation.hpp#L1491C1-L1508C74)), and will be documented when #551 gets merged. Happy to close this issue @james-d-mitchell?

**Comment by james-d-mitchell** [comment]
Yup let's close this
