### ISSUE TITLE
Segfault with `Paths.count`

### ISSUE THREAD

**Issue by MTWhyte** [libsemigroups/libsemigroups#486]
After importing the `Paths` member `count` to `libsemigroups_pybind11`, I find that the following produces a segfault:

```
In [1]: from libsemigroups_pybind11 import Paths, algorithm

In [2]: p = Paths()

In [3]: p.count()
```

**Comment by MTWhyte** [comment]
We have decided to rename `from` and `to`, `source` and `target`, respectively, since `from` is also a Python keyword. Getting them both working in essentially the same way in `libsemigroups_pybind11`,  I find that `target` can produce a segfault where `source` does not:

```
In [1]: from libsemigroups_pybind11 import Paths

In [2]: p = Paths()

In [3]: p.source()
Out[3]: 4294967295

In [4]: p.target()
<SEGFAULT>
```

**Comment by james-d-mitchell** [comment]
Thanks for the report @MTWhyte, I have the memory that you fixed this already, is that correct? If so, please close this issue!

Thanks!

**Comment by MTWhyte** [comment]
Yeah, I think this is fixed! Or fixed in the sense that this wasn't an issue with `main`, but something that came up when getting the refactored `libsemigroups` stuff working, which I believe I have addressed in my work-in-progress.
