### ISSUE TITLE
`test_ranges [003]` sometimes fails

### ISSUE THREAD

**Issue by Joseph-Edwards** [libsemigroups/libsemigroups#594]
This was prompted by [this job](https://github.com/libsemigroups/libsemigroups/actions/runs/10738732457/job/29782920672?pr=593) unexpectedly failing in #593 with this message:

``` bash
[003]: Ranges 003: Random                                          
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
test_all is a Catch v2.13.10 host application.
Run with -? for options

-------------------------------------------------------------------------------
Ranges 003: Random
-------------------------------------------------------------------------------
tests/test-ranges.cpp:70
...............................................................................

tests/test-ranges.cpp:76: FAILED:
  REQUIRE( val < 100 )
with expansion:
  100 < 100
```

Seems like an off-by-one error to me.

**Comment by james-d-mitchell** [comment]
Hmm maybe, although also maybe not. I'm pretty sure that:

~~~
(rx::seq() | rx::take(100))
~~~
(which generates `val`) is supposed to be the numbers 0 to 99. So it ought not to be possible for there to be a value of 100 coming out of this. Let me investigate...

**Comment by james-d-mitchell** [comment]
No you're right, unlike everywhere else in C++ `std::uniform_int_distribution<T>(a, b)`

> Produces random integer values $i$, uniformly distributed on the closed interval $[a, b]$.

Should be easy to resolve by just subtracting 1 in:

https://github.com/libsemigroups/libsemigroups/blob/bc2a7202a747214d153f3404153ac860dc28f779/include/libsemigroups/ranges.tpp#L37
